###

GET http://localhost:3000/api/businesses

###

GET http://localhost:3000/api/businesses/5

###

GET http://localhost:3000/api/bags

###

GET http://localhost:3000/api/bags/1

###
GET http://localhost:3000/api/businesses/4/bags

###