###

GET http://localhost:3000/api/businesses

###

POST http://localhost:3000/api/businesses
Content-Type: application/json

{
    "name": "Flower Burgers",
    "address": "via Po 15",
    "phoneNumber": 3333333,
    "cuisineType": "vegan",
    "foodCategory": null
}

###

GET http://localhost:3000/api/businesses/

###

PUT http://localhost:3000/api/businesses/1
Content-Type: application/json

{
    "name": "Flower Burgers",
    "address": "via Po 15",
    "phoneNumber": 333,
    "cuisineType": "vegan",
    "foodCategory": null
}

###

PUT http://localhost:3000/api/businesses/99
Content-Type: application/json

{
    "name": "Flower Burgers",
    "address": "via Po 15",
    "phoneNumber": 333,
    "cuisineType": "vegan",
    "foodCategory": null
}

###

GET http://localhost:3000/api/bags

###

GET http://localhost:3000/api/bags/1

###

GET http://localhost:3000/api/businesses/1/bags

###

POST http://localhost:3000/api/businesses/1/bags
Content-Type: application/json

{
    "bagType": "Surprise",
    "foodItems": [
        {
            "name": "pizza",
            "quantity": 4
        },
        {
            "name": "farinata",
            "quantity": 2
        }
    ],
    "price": 14.00,
    "size": "large",
    "timestampStart": "2025-04-27",
    "timestampEnd": "2025-04-29"
}


###

GET http://localhost:3000/api/bags/1/fooditems
